---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nginxdeployment
  namespace: fluxname
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/adminturneddevops/PearsonCourses
